function zd=trebdsgn(command,parameter1,parameter2,parameter3) 
%TREBDSGN Simulates the throw of a Trebuchet and estimates
%maximum distance an object could be thrown if released at
%the right time. The help for TREBDSGN is much more helpful
%if accessed from withing TREBDSGN. Type TREBDSGN (in lower 
%case) and select the red help button.
%
%TREBDSGN allows you to interactively enter design variables
%and obtain performance estimates for the trebuchet shown.
%The trebuchet as shown throws the object to the left. The
%counter mass is at the left hanging from the rope, and the 
%projectile is on the ground at the otherend of the device.
%Apon release, the counter mass drops, and the projectile 
%is dragged to the right initially, then it continues in a 
%counter clockwise fashion about the pivot point. Select 
%"show movies" and push "go" to simulate the motion and show 
%a movie of it. The meanings of the variables on the right 
%hand side of the main window are shown in the figure above 
%and in descriptions below. Various bits of simulation re-
%sults are available by selecting the appropriate check boxes 
%to the bottom left. All units used must be consistant units. 
%For SI, use kg-m-s (N) units, and for English units, use 
%slug-ft-s (lbf) units. All angles are in radians.
%
%                     VARIABLE DEFINITIONS
%  
%  l1, l2, l3, and l5 are clear from the diagram.
%  l4       is the distance from the pivot point to the center 
%              of the lever arm.
%  m1       is the mass of the counterweight.
%  m2       is the mass of the lever arm.
%  m3       is the mass of the projectile.
%  J        is the mass moment of inertia of the lever arm. 
%              For a uniform cross section arm, it is equal to
%              m2*((l2+l5)^2)/12+l4^2)
%  T Final  is the total simulation time. 
%  Height   is the height of the trebuchet pivot point above 
%              the ground.
%  Phi Init is the initial amount the trebuchet is cocked in 
%              radians. It is zero when the counter mass is 
%              directly above the pivot point. 0 is better.
%              In plots, it is the angle Phi2.
%  Phi1, Phi2, Phi3 are shown in the figure above. They can be
%              viewed as a function of simulated time by 
%              selecting the appropriate checkboxes before
%              a simulation run.
%             
%  To change any of the variables, select the appropriate box
%  and edit the variable. The variable will be accepted when
%  you hit return (or enter) or when you select another box.
%  



%
%  If you don't think this is helpfull enough, blame Dr. Thomas.
%  He's the one whose supposed to improve this help.
%  His email can easily be flooded at sthomas@delta.cs.wright.edu
%  Just send email until he gives up.

%  You can also egg his blue truck. (Note how this doesn't show up
%  when you type help.)

 
%  If you rename this file: 
%    1. Replace all occurrences of 'trebdsgn' with desired 'filename'. 
%    2. Resave this file as that 'filename'. 
%   
%  To edit callbacks : 
%          Fill in the 'elseif command == ...' sections with 
%          code that does something other than what was  
%          defined in GUIMaker 2.0. Be creative! 
%          The code must lie between the CALLBACK_START and  
%          CALLBACK_STOP comments for each objects callback  
%          command section if you want to be able to edit 
%          the GUI with GUIMaker later on and not lose the 
%          callback information. 
%   
%  trebdsgn.m 
%   
%  usage:       trebdsgn(command,parameter1) 
%   
%           where 
%   
%               'command' is used to perform some defined operation 
%               'parameter1' can be used pass extra information 
%                              to a defined operation 
%   
%           If no arguements are used the GUI is initialized. 
%   

%  Created: 12-Dec-96 
%  Using  : GUI Maker Ver 2.0 by Patrick Marchand 
%                         (pmarchan@motown.ge.com) 
%  Author : Joseph C. Slater, PhD
%  Mods.  : 1-17-98 Added Plot Control Buttons
%         : 1-18-98 Separated trebint to speed up integration
%   

%  Copyright (c)   Joseph C. Slater
%   No permission is granted to modify or re-distribute this 
%	code in any manner. 
%	All standard disclaimers apply. 


global l1 l2 l3 l4 l5 m1 m2 m3 g h N mu i lt M J trlines int_time tintt
global xmin xmax ymin ymax phi1init phi2init phi3init flag5 dmax h_uic_15
g=9.806;
mu=.01;
fs=1/3;
flag2=0;
if nargin==4
%parameter1,parameter2,parameter3
end
time=[];
if nargin == 0 
	command = 'new'; 
end 

if isstr(command) 
	if strcmp(lower(command),'initialize') | strcmp(lower(command),'new') 
		command = 0; 
	elseif strcmp(lower(command),lower('h_uic_16')) 
		command = 1; 
	elseif strcmp(lower(command),lower('h_uic_1')) 
		command = 2; 
	elseif strcmp(lower(command),lower('h_uic_13')) 
		command = 3; 
	elseif strcmp(lower(command),lower('h_uic_12')) 
	 	command = 4; 
	elseif strcmp(lower(command),lower('h_uic_11')) 
		command = 5; 
	elseif strcmp(lower(command),lower('h_uic_10')) 
		command = 6; 
	elseif strcmp(lower(command),lower('h_uic_9')) 
		command = 7; 
	elseif strcmp(lower(command),lower('h_uic_8')) 
		command = 8; 
	elseif strcmp(lower(command),lower('h_uic_7')) 
		command = 9; 
	elseif strcmp(lower(command),lower('h_uic_6')) 
		command = 10; 
	elseif strcmp(lower(command),lower('h_uic_5')) 
		command = 11; 
	elseif strcmp(lower(command),lower('h_uic_4')) 
		command = 12; 
	elseif strcmp(lower(command),lower('h_uic_3')) 
		command = 13; 
	elseif strcmp(lower(command),lower('h_uic_2')) 
		command = 14; 
	end 
end 

if command ~= 0 
	h_fig_list = findobj(get(0,'children'),'flat',... 
		'tag','trebdsgn'); 
		if length(h_fig_list) > 1 
			h_fig_list = gcf; 
		elseif length(h_fig_list) == 0 
			error('There are no figures with Tag = trebdsgn.'); 
		end 
	handle_list = get(h_fig_list,'userdata'); 
	if length(handle_list) > 0 
		h_uic_16 = handle_list(1); 
		h_uic_1 = handle_list(2); 
		h_uic_13 = handle_list(3); 
		h_uic_12 = handle_list(4); 
		h_uic_11 = handle_list(5); 
		h_uic_10 = handle_list(6); 
		h_uic_9 = handle_list(7); 
		h_uic_8 = handle_list(8); 
		h_uic_7 = handle_list(9); 
		h_uic_6 = handle_list(10); 
		h_uic_5 = handle_list(11); 
		h_uic_4 = handle_list(12); 
		h_uic_3 = handle_list(13); 
		h_uic_2 = handle_list(14); 
		h_uic_15 = handle_list(15); 
		h_axes_1 = handle_list(16); 
		h_text_2 = handle_list(17); 
		h_text_13 = handle_list(18); 
		h_text_12 = handle_list(19); 
		h_text_11 = handle_list(20); 
		h_text_10 = handle_list(21); 
		h_text_9 = handle_list(22); 
		h_text_8 = handle_list(23); 
		h_text_7 = handle_list(24); 
		h_text_6 = handle_list(25); 
		h_text_5 = handle_list(26); 
		h_text_4 = handle_list(27); 
		h_text_3 = handle_list(28); 
		h_text_1 = handle_list(29); 
	end 
    l1 = str2num(get(h_uic_2,'string'));
    l2 = str2num(get(h_uic_3,'string'));
    l3 = str2num(get(h_uic_4,'string'));
    l4 = str2num(get(h_uic_5,'string'));
    l5 = str2num(get(h_uic_6,'string'));
    m1 = str2num(get(h_uic_7,'string'));
    m2 = str2num(get(h_uic_8,'string'));
    m3 = str2num(get(h_uic_9,'string'));
    J  = str2num(get(h_uic_10,'string'));
    simtime = str2num(get(h_uic_11,'string'));
    h = str2num(get(h_uic_12,'string'));
    phi2 = str2num(get(h_uic_13,'string'));

end 
on=	[ 0.83 0.085 0.096 0.054 ];
off= on;%[ 0.13 0.08 0.087 0.054 ];


if command == 0 & nargin~=2

	fig = findobj(get(0,'children'),'flat','tag','trebdsgn'); 
	if length(fig) > 0 
		set(fig,'visible','on'); 
		figure(fig); 
		return; 
	end 
	
	fig = figure('units','normal','position',[ .15 .25 .7 .7 ],... 
		'resize','On','tag','trebdsgn',... 
		'menubar','Figure','name','Trebuchet Designer 2.0',... 
		'numbertitle','Off','visible','off'); 
	tc=hsv2rgb([rand(1,1) 1 1]);
	set(fig,'color',tc)
		

	%  Uicontrol Object Creation 
	frame=uicontrol(gcf,'style','frame',...
	    'units','normalized',...
		'position',[.75 0.0 .25 1],...
		'position',[.75 0.00 0.25 1]);
	
	frame=uicontrol(gcf,'style','frame',...
        'Tag','BottomFrame',...
	    'units','normalized',...
		'position',[0.02 0.00 .72 .14]);

		
		% This is stuff added later
		%----------------------------------------------
	b = uicontrol('Units','normalized', ...
		'FontUnits','normalized', ...
		'BackgroundColor',[0.733333 0.733333 0.733333], ...
		'FontSize',0.333333, ...
		'Position',[0.5807143 0.0190476 0.150714 0.0452381], ...
		'String','Show Movies', ...
		'Style','checkbox', ...
		'Tag','ShowMovies');
	b = uicontrol('Units','normalized', ...
		'FontUnits','normalized', ...
		'BackgroundColor',[0.733333 0.733333 0.733333], ...
		'FontSize',0.333333, ...
		'Position',[0.307143 0.0190476 0.260714 0.0452381], ...
		'String','Plot distance vrs time', ...
		'Style','checkbox', ...
		'Tag','Distance');
	b = uicontrol('Units','normalized', ...
		'FontUnits','normalized', ...
		'BackgroundColor',[0.733333 0.733333 0.733333], ...
		'FontSize',0.333333, ...
		'Position',[0.0464286 0.0785714 0.260714 0.0452381], ...
		'String','Plot Phi1 vrs. time', ...
		'Style','checkbox', ...
		'Tag','Phi1');
	b = uicontrol('Units','normalized', ...
		'FontUnits','normalized', ...
		'BackgroundColor',[0.733333 0.733333 0.733333], ...
		'FontSize',0.333333, ...
		'Position',[0.0464286 0.0190476 0.260714 0.0452381], ...
		'String','Plot Phi2 vrs. time', ...
		'Style','checkbox', ...
		'Tag','Phi2');
	b = uicontrol('Units','normalized', ...
		'FontUnits','normalized', ...
		'BackgroundColor',[0.733333 0.733333 0.733333], ...
		'FontSize',0.333333, ...
		'Position',[0.307143 0.0785714 0.260714 0.0452381], ...
		'String','Plot Phi3 vrs. time', ...
		'Style','checkbox', ...
		'Tag','Phi3');
	b = uicontrol('Units','normalized', ...
		'FontUnits','normalized', ...
		'BackgroundColor',  [0.9804    0.3059    0.0980],...%[0.7 0 0], ...
		'FontSize',0.45, ...
		'Position',[0.594643 0.08 0.132143 0.05], ...
		'String','Help', ...
		'Callback','trh',...
		'Tag','Help');
		%--------------------------------------------

	
	
		

gui_h1=.05  ; % Height of text in boxes
gui_h2=.06  ; % Height of Buttons
gui_w1=.10 ; % Width of text in boxes
gui_w2=.170 ; % Width of buttons
gui_xt=.80 ; % X location of text labels
gui_xti=.89; % x location of text in
gui_ys=.0    ; % yshift of text in relative to label
gui_y=.933:-(.933-.02)/13:.02; % Y Location of text
gui_yt= gui_y; % Y Location of text;
gui_sy=0+.003*0-.007;
gui_wl=.08    ;% width of labels

	h_uic_16 = uicontrol(... 
		'CallBack','trebdsgn(''h_uic_16'');',... 
		'String','Replay',... 
		'backgroundcolor',[ 0.1421    0.8379    0.2580],...
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Position',off,... 
		'Tag','h_uic_16',... 
		'UserData','',...
		'visible','off'); 
	h_uic_1 = uicontrol(... 
		'CallBack',...%pack;
		'trebdsgn(''h_uic_1'');',... 
		'backgroundcolor',[ 0.1421    0.8379    0.2580],...
		'String','Go',... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Position',on,... 
		'Tag','h_uic_1',... 
		'interruptible','off',...
		'UserData',''); 
	h_uic_13 = uicontrol(... 
		'CallBack','trebdsgn(''h_uic_13'');',... 
		'String','0.8588',... 
		'Style','edit',... 
		'backgroundcolor',[1 1 1],...
		'Units','normalized',... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'HorizontalAlignment','Left',...
		'Position',[ gui_xti gui_y(12) gui_w1 gui_h1 ],... 
		'Tag','h_uic_13',... 
		'UserData',''); 
	h_uic_12 = uicontrol(... 
		'CallBack','trebdsgn(''h_uic_12'');',... 
		'String','0.35',... 
		'Style','edit',... 
		'backgroundcolor',[1 1 1],...
		'FontUnits','normalized',...
		'FontSize',fs,...
		'HorizontalAlignment','Left',...
		'Units','normalized',... 
		'Position', [ gui_xti gui_y(11) gui_w1 gui_h1 ],... 
		'Tag','h_uic_12',... 
		'UserData',''); 
	h_uic_11 = uicontrol(... 
		'CallBack','trebdsgn(''h_uic_11'');',... 
		'String','0.55',... 
		'Style','edit',... 
		'backgroundcolor',[1 1 1],...
		'Units','normalized',... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'HorizontalAlignment','Left',...
		'Position', [ gui_xti gui_y(10) gui_w1 gui_h1 ],... 
		'Tag','h_uic_11',... 
		'UserData',''); 
	h_uic_10 = uicontrol(... 
		'CallBack','trebdsgn(''h_uic_10'');',... 
		'String','0.0069',... 
		'Style','edit',... 
		'backgroundcolor',[1 1 1],...
		'Units','normalized',... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'HorizontalAlignment','Left',...
		'Position', [ gui_xti gui_y(9) gui_w1 gui_h1 ],... 
		'Tag','h_uic_10',... 
		'UserData',''); 
	h_uic_9 = uicontrol(... 
		'CallBack','trebdsgn(''h_uic_9'');',... 
		'String','0.0057',... 
		'Style','edit',... 
		'backgroundcolor',[1 1 1],...
		'Units','normalized',... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'HorizontalAlignment','Left',...
		'Position', [ gui_xti gui_y(8) gui_w1 gui_h1 ],... 
		'Tag','h_uic_9',... 
		'UserData',''); 
	h_uic_8 = uicontrol(... 
		'CallBack','trebdsgn(''h_uic_8'');',... 
		'String','0.12',... 
		'Style','edit',... 
		'backgroundcolor',[1 1 1],...
		'Units','normalized',... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'HorizontalAlignment','Left',...
		'Position', [ gui_xti gui_y(7) gui_w1 gui_h1 ],... 
		'Tag','h_uic_8',... 
		'UserData',''); 
	h_uic_7 = uicontrol(... 
		'CallBack','trebdsgn(''h_uic_7'');',... 
		'String','0.64',... 
		'Style','edit',... 
		'backgroundcolor',[1 1 1],...
		'Units','normalized',... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'HorizontalAlignment','Left',...
		'Position', [ gui_xti gui_y(6) gui_w1 gui_h1 ],... 
		'Tag','h_uic_7',... 
		'UserData',''); 
	h_uic_6 = uicontrol(... 
		'CallBack','trebdsgn(''h_uic_6'');',... 
		'String','0.535',... 
		'Style','edit',... 
		'Units','normalized',... 
		'backgroundcolor',[1 1 1],...
		'FontUnits','normalized',...
		'FontSize',fs,...
		'HorizontalAlignment','Left',...
		'Position', [ gui_xti gui_y(5) gui_w1 gui_h1 ],... 
		'Tag','h_uic_6',... 
		'UserData',''); 
	h_uic_5 = uicontrol(... 
		'CallBack','trebdsgn(''h_uic_5'');',... 
		'String','0.14',... 
		'Style','edit',... 
		'backgroundcolor',[1 1 1],...
		'Units','normalized',... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'HorizontalAlignment','Left',...
		'Position', [ gui_xti gui_y(4) gui_w1 gui_h1 ],... 
		'Tag','h_uic_5',... 
		'UserData',''); 
	h_uic_4 = uicontrol(... 
		'CallBack','trebdsgn(''h_uic_4'');',... 
		'String','0.37',... 
		'Style','edit',... 
		'backgroundcolor',[1 1 1],...
		'Units','normalized',... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'HorizontalAlignment','Left',...
		'Position', [ gui_xti gui_y(3) gui_w1 gui_h1 ],... 
		'Tag','h_uic_4',... 
		'UserData',''); 
	h_uic_3 = uicontrol(... 
		'CallBack','trebdsgn(''h_uic_3'');',... 
		'String','0.09',... 
		'Style','edit',... 
		'backgroundcolor',[1 1 1],...
		'Units','normalized',... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'HorizontalAlignment','Left',...
		'Position', [ gui_xti gui_y(2) gui_w1 gui_h1 ],... 
		'Tag','h_uic_3',... 
		'UserData',''); 
	h_uic_2 = uicontrol(... 
		'CallBack','trebdsgn(''h_uic_2'');',... 
		'String','0.1',... 
		'Style','edit',... 
		'backgroundcolor',[1 1 1],...
		'Units','normalized',... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'HorizontalAlignment','Left',...
		'Position', [ gui_xti gui_y(1) gui_w1 gui_h1 ],... 
		'Tag','h_uic_2',... 
		'UserData',''); 
	h_uic_15 = uicontrol(... 
		'CallBack','trebdsgn(''h_uic_15'');',... 
		'Style','text',... 
		'String','Enter values at will',...
		'Units','normalized',... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'Position',[ 0.77 0.017 0.22 0.047 ],... 
		'Tag','h_uic_15',... 
		'UserData',''); 


	%  Menu Object Creation 


	%  Axes and Text Object Creation 

	h_axes_1 = axes(... 
		'Units','normalized', ... 
		'Tag','Axes',...
		'Position',[ 0.05 0.10 0.66 0.9 ],... 
		'Xgrid','off', ... 
		'Ygrid','off', ... 
		'Xlim',[ 0 1 ],... 
		'Ylim',[ 0 1 ],... 
		'Clipping','on', ... 
		'Tag','h_axes_1', ... 
		'UserData','');	
	h_text_2 = uicontrol(... 
		'String','l1', ... 
		'Style','text',... 
		'Units','normalized', ... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'Position',[ gui_xt gui_yt(1)+gui_sy gui_wl .047 ],... 
		'Tag','h_text_2', ... 
		'UserData',''); 
	h_text_13 = uicontrol(... 
		'String','Phi Init.', ... 
		'Style','text',... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'Units','normalized', ... 
		'Position',[ gui_xt gui_yt(12)+gui_sy gui_wl .047 ],... 
		'Tag','h_text_13', ... 
		'UserData',''); 
	h_text_12 = uicontrol(... 
		'String','Height', ... 
		'Style','text',... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'Units','normalized', ... 
		'Position',[ gui_xt gui_yt(11)+gui_sy gui_wl .047 ],... 
		'Tag','h_text_12', ... 
		'UserData',''); 
	h_text_11 = uicontrol(... 
		'String','T Final', ... 
		'Style','text',... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'Units','normalized', ... 
		'Position',[ gui_xt gui_yt(10)+gui_sy gui_wl .047 ],... 
		'Tag','h_text_11', ... 
		'UserData',''); 
	h_text_10 = uicontrol(... 
		'String','J', ... 
		'Style','text',... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'Units','normalized', ... 
		'Position',[ gui_xt gui_yt(9)+gui_sy gui_wl .047 ],... 
		'Tag','h_text_10', ... 
		'UserData',''); 
	h_text_9 = uicontrol(... 
		'String','m3', ... 
		'Style','text',... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'Units','normalized', ... 
		'Position',[ gui_xt gui_yt(8)+gui_sy gui_wl .047 ],... 
		'Tag','h_text_9', ... 
		'UserData',''); 
	h_text_8 = uicontrol(... 
		'String','m2', ... 
		'Style','text',... 
		'Units','normalized', ... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'Position',[ gui_xt gui_yt(7)+gui_sy gui_wl .047 ],... 
		'Tag','h_text_8', ... 
		'UserData',''); 
	h_text_7 = uicontrol(... 
		'String','m1', ... 
		'Style','text',... 
		'Units','normalized', ... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'Position',[ gui_xt gui_yt(6)+gui_sy gui_wl .047 ],... 
		'Tag','h_text_7', ... 
		'UserData',''); 
	h_text_6 = uicontrol(... 
		'String','l5', ... 
		'Style','text',... 
		'Units','normalized', ... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'Position',[ gui_xt gui_yt(5)+gui_sy gui_wl .047 ],... 
		'Tag','h_text_6', ... 
		'UserData',''); 
	h_text_5 = uicontrol(... 
		'String','l4', ... 
		'Style','text',... 
		'Units','normalized', ... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'Position',[ gui_xt gui_yt(4)+gui_sy gui_wl .047 ],... 
		'Tag','h_text_5', ... 
		'UserData',''); 
	h_text_4 = uicontrol(... 
		'String','l3', ... 
		'Style','text',... 
		'Units','normalized', ... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'Position',[ gui_xt gui_yt(3)+gui_sy gui_wl .047 ],... 
		'Tag','h_text_4', ... 
		'UserData',''); 
	h_text_3 = uicontrol(... 
		'String','l2', ... 
		'Style','text',... 
		'Units','normalized', ... 
		'FontUnits','normalized',...
		'FontSize',fs,...
		'Position',[ gui_xt gui_yt(2)+gui_sy gui_wl .047 ],... 
		'Tag','h_text_3', ... 
		'UserData',''); 
	h_text_1 = text(... 
		'Units','normalized', ... 
		'Position',[ gui_xt .943 0 ],... 
		'String','',...
		'FontUnits','normalized',...
		'FontSize',fs,...
		'Tag','h_text_1', ... 
		'UserData',''); 



	handle_list = [ ...  
	 	 h_uic_16 h_uic_1 h_uic_13 ... 
	 	h_uic_12 h_uic_11 h_uic_10 h_uic_9 ... 
	 	h_uic_8 h_uic_7 h_uic_6 h_uic_5 ... 
	 	h_uic_4 h_uic_3 h_uic_2 h_uic_15 ... 
	 	 h_axes_1  h_text_2 ... 
	 	h_text_13 h_text_12 h_text_11 h_text_10 ... 
	 	h_text_9 h_text_8 h_text_7 h_text_6 ... 
	 	h_text_5 h_text_4 h_text_3 h_text_1 ... 
	 	 	]; 

	set(gcf,'userdata',handle_list); 
	drawnow;pause(.01); 
	trebdsgn('grphinit')
%	phi1init,phi2init,phi3init
	trebdsgn('plot',phi1init,phi2init,phi3init)
    drawnow;
   	set(gcf,'visible','on'); 

	trh('i');%Creates help window invisibly so it can load faster.
	figure('tag','trebplot','visible','off')

elseif command == 1 & nargin~=2
	%disp('h_uic_16 selected.') 
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_START h_uic_16 
%	set(h_uic_1,'visible','on','position',off)
%	set(h_uic_16,'visible','off','position',on)
    movie(M)
    movie(M(:,1))
%	trebdsgn('plot',phi1init,phi2init,phi3init)
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_STOP h_uic_16 
elseif command == 2 & nargin~=2
%	disp('h_uic_1 selected.') 
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_START h_uic_1 
	lt=0;
	if tintt>0
		str15=['Please wait ~' num2str(tintt) ' sec'];
	else 
		str15=['Integrating, please wait'];
	end
	set(h_uic_15,'string',str15)
	drawnow
	options = odeset('RelTol',1e-3);
	tic
	[int_time,z]=ode23('trebint',[0,simtime], [phi1init;0;phi2init;0;phi3init;0],options);
	tintt=round(toc);
%	[int_time,z]=ode23('trebdsgn',0,simtime, [phi1init;0;phi2init;0;phi3init;0],1e-6);
%    [int_time,z]=ode45('trebdiff',0,simtime, [phi1init;0;phi2init;0;phi3init;0],.1);
%    int_time= [0:.1:simtime];
%    z=vtb9_3('trebdiff',zeros(6,length(int_time)), int_time, [phi1init;0;phi2init;0;phi3init;0]);
%	size(z);
	z=z';
	phi1=z(1,:);
    phi2=z(3,:);
    phi3=z(5,:);
	phi1d=z(2,:);
    phi2d=z(4,:);
    phi3d=z(6,:);
    x0=l5 * sin(phi2)+l3 * sin(phi3);
	y0=-l5 * cos(phi2)-l3 * cos(phi3);
	y0=y0+h;
    vx=l5*phi2d.*cos(phi2)+l3*phi3d.*cos(phi3);
    vy=l5*phi2d.*sin(phi2)+l3*phi3d.*sin(phi3);
    dmax=-(vx/g.*(vy+sqrt(vy.^2+2*g*y0))+x0);
    [dimax,imax]=max(dmax);
    if max(phi2)<pi
        set(h_uic_15,'string','T max is too low')
        pause(2)
        set(h_uic_11,'string',num2str(simtime*1.5))
        set(h_uic_15,'string','T has been increased'),pause(1)
        trebdsgn('h_uic_1')
        return
      else
	    set(h_uic_15,'string',['dmax = ' num2str(dimax)])
	    set(h_uic_11,'string',num2str(int_time(imax)*1.4))


        playmovie=get(findobj('Tag','ShowMovies'),'value');
		
		if playmovie==1
		    frames=14;% Number of frames in movie
	
	
		    nt=0:simtime/(frames-1):simtime;
		    mphi1=interp1(int_time',phi1',nt','spline');phi1(1);
		    mphi2=interp1(int_time',phi2',nt','spline');phi2(1);
		    mphi3=interp1(int_time',phi3',nt','spline');phi3(1);
		    lnt=length(nt);
		    M=[];
		    M = moviein(lnt);
		    for ii=1:lnt
              trebdsgn('plot',mphi1(ii),mphi2(ii),mphi3(ii));
		      M(:,ii) = getframe;
		    end
            
		    movie(M)
		    movie(M(:,1))
			set(h_uic_1,'visible','off')
			set(h_uic_16,'position',on,'visible','on')
	    end
	
		pd=get(findobj('Tag','Distance'),'Value');
		pphi1=get(findobj('Tag','Phi1'),'Value');
		pphi2=get(findobj('Tag','Phi2'),'Value');
		pphi3=get(findobj('Tag','Phi3'),'Value');
		
		if (pd+pphi1+pphi2+pphi3)>0
			if isempty(findobj('tag','trebplot')) & isempty(findobj('tag','trebhelp'))
				trh('i')
			    dtfn=figure('tag','trebplot','visible','off');
			elseif ~isempty(findobj('tag','trebplot')) & isempty(findobj('tag','trebhelp'))
				dtfn=findobj('tag','trebplot');
				if size(dtfn,1)>1
					dtfntemp=min(dtfn);
					delete(dtfn)
					dtfn=dtfntemp;
				end
				figure(dtfn);
				trh('i')
			elseif isempty(findobj('tag','trebplot')) & ~isempty(findobj('tag','trebhelp'))
			    dtfn=figure('tag','trebplot','visible','off');
			elseif ~isempty(findobj('tag','trebplot')) & ~isempty(findobj('tag','trebhelp'))
				dtfn=findobj('tag','trebplot');
				if size(dtfn,1)>1
					dtfntemp=min(dtfn);
					delete(dtfn)
					dtfn=dtfntemp;
				end
				figure(dtfn);
			end
			if size(dtfn,1)>1
				dtfntemp=min(dtfn);
				delete(dtfn)
				dtfn=dtfntemp;
			end
			figure(dtfn)
				
	
						
			uicontrol('style','pushbutton','units','normal','position',[.91 .95 .075...
		    .05],'string','Print','callback','print')
		    uicontrol('style','pushbutton','units','normal','position',[.91 .89 .075...
		    .05],'string','Close','callback','delete(gcf)')
		%	cbdtfn)

			if pd
				if (pphi1+pphi2+pphi3)>0
					subplot(2,1,1)
				end
				cbdtfn=['delete(' num2str(dtfn) ')'];
				plot(int_time,dmax)
				grid on
				zoom on
				xlabel('Release Time (sec)')
				ylabel('Distance thrown (m)')
			end
%   Continue and make other plots here
			if (pphi1+pphi2+pphi3)>0
				if pd
					subplot(2,1,2)
				end
				pphi=[pphi1 pphi2 pphi3];
				Phi=[];
				Lphi=[];
				phi=[phi1' phi2' phi3'];
				for i=1:3
					if pphi(i)
						Phi=[Phi phi(:,i)];
						Lphi=[Lphi;'Phi' num2str(i)];
					end
				end
				plot(int_time',Phi)
				grid on
				zoom on
				legend(Lphi)
				xlabel('Time (sec)')
				ylabel('Angle (radians)')
			end
			set(dtfn,'visible','off')
			set(dtfn,'visible','on')
			figure(dtfn)

		end
	end
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_STOP h_uic_1 
elseif command == 3 & nargin~=2
	%disp('h_uic_13 selected.') 
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_START h_uic_13 
	if phi2<0 | phi2 > pi/2
    	set(h_uic_15,'string','Phi out of range'),pause(2)
    	pause(3)
    	set(h_uic_13,'string',num2str(0))
    	set(h_uic_15,'string','Phi reset to 0')
    	drawnow
    end
	trebdsgn('grphinit')
	flag5=1;
	trebdsgn('plot',phi1init,phi2init,phi3init)
	set(h_uic_1,'visible','on','position',on)
	set(h_uic_15,'string','Enter values')
	set(h_uic_16,'visible','off','position',off)
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_STOP h_uic_13 
elseif command == 4 & nargin~=2
	%disp('h_uic_12 selected.') 
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_START h_uic_12 
	trebdsgn('grphinit')
	trebdsgn('plot',phi1init,phi2init,phi3init)
	set(h_uic_1,'visible','on','position',on)
	set(h_uic_15,'string','Enter values')
	set(h_uic_16,'visible','off','position',off)
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_STOP h_uic_12 
elseif command == 5 & nargin~=2
	%disp('h_uic_11 selected.') 
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_START h_uic_11 
%	trebdsgn('grphinit')
%	trebdsgn('plot',phi1init,phi2init,phi3init)
	set(h_uic_1,'visible','on','position',on)
	set(h_uic_15,'string','Enter values')
	set(h_uic_16,'visible','off','position',off)
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_STOP h_uic_11 
elseif command == 6 & nargin~=2
	%disp('h_uic_10 selected.') 
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_START h_uic_10 
%	trebdsgn('grphinit')
%	trebdsgn('plot',phi1init,phi2init,phi3init)
	set(h_uic_1,'visible','on','position',on)
	set(h_uic_15,'string','Enter values')
	set(h_uic_16,'visible','off','position',off)
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_STOP h_uic_10 
elseif command == 7 & nargin~=2
	%disp('h_uic_9 selected.') 
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_START h_uic_9 
%	trebdsgn('grphinit')
%	trebdsgn('plot',phi1init,phi2init,phi3init)
	set(h_uic_1,'visible','on','position',on)
	set(h_uic_15,'string','Enter values')
	set(h_uic_16,'visible','off','position',off)
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_STOP h_uic_9 
elseif command == 8 & nargin~=2
	%disp('h_uic_8 selected.') 
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_START h_uic_8 
%	trebdsgn('grphinit')
%	trebdsgn('plot',phi1init,phi2init,phi3init)
	set(h_uic_1,'visible','on','position',on)
	set(h_uic_15,'string','Enter values')
	set(h_uic_16,'visible','off','position',off)
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_STOP h_uic_8 
elseif command == 9 & nargin~=2
	%disp('h_uic_7 selected.') 
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_START h_uic_7 
%	trebdsgn('grphinit')
%	trebdsgn('plot',phi1init,phi2init,phi3init)
	set(h_uic_1,'visible','on','position',on)
	set(h_uic_15,'string','Enter values')
	set(h_uic_16,'visible','off','position',off)
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_STOP h_uic_7 
elseif command == 10 & nargin~=2
	%disp('h_uic_6 selected.') 
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_START h_uic_6 
	trebdsgn('grphinit')
	trebdsgn('plot',phi1init,phi2init,phi3init)
	set(h_uic_1,'visible','on','position',on)
	set(h_uic_15,'string','Enter values')
	set(h_uic_16,'visible','off','position',off)
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_STOP h_uic_6 
elseif command == 11 & nargin~=2
	%disp('h_uic_5 selected.') 
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_START h_uic_5 
	trebdsgn('grphinit')
	trebdsgn('plot',phi1init,phi2init,phi3init)
	set(h_uic_1,'visible','on','position',on)
	set(h_uic_15,'string','Enter values')
	set(h_uic_16,'visible','off','position',off)
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_STOP h_uic_5 
elseif command == 12 & nargin~=2
	%disp('h_uic_4 selected.') 
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_START h_uic_4 
	trebdsgn('grphinit')
	trebdsgn('plot',phi1init,phi2init,phi3init)
	set(h_uic_1,'visible','on','position',on)
	set(h_uic_15,'string','Enter values')
	set(h_uic_16,'visible','off','position',off)
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_STOP h_uic_4 
elseif command == 13 & nargin~=2
	%disp('h_uic_3 selected.') 
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_START h_uic_3 
	trebdsgn('grphinit')
	trebdsgn('plot',phi1init,phi2init,phi3init)
	set(h_uic_1,'visible','on','position',on)
	set(h_uic_15,'string','Enter values')
	set(h_uic_16,'visible','off','position',off)
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_STOP h_uic_3 
elseif command == 14 & nargin~=2
	%disp('h_uic_2 selected.') 
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_START h_uic_2 
	trebdsgn('grphinit')
	trebdsgn('plot',phi1init,phi2init,phi3init)
	set(h_uic_1,'visible','on','position',on)
	set(h_uic_15,'string','Enter values')
	set(h_uic_16,'visible','off','position',off)
	%%       DO NOT REMOVE/ALTER THIS COMMENT: CALLBACK_STOP h_uic_2 
elseif strcmp(command,'grphinit')

	flag5=0;
	if l1+l2>h
	     set(h_uic_15,'string','l1 is too big'),pause(2)
	     set(h_uic_2,'string',num2str(h-l2))
	     drawnow
	     flag2=1;
	end     
	phi1=0;
	
	phi3=0;
	
	y3=-l5*cos(phi2)-l3*cos(phi3);
	
	if l5*cos(phi2)>h
	     phi2=acos(h/l5)+.001;
	     set(h_uic_13,'string',num2str(phi2))
	     set(h_uic_15,'String','h too small for phi'),pause(2)
	   else
	     set(h_uic_15,'string','Enter values at will')
	end
	
	flag=1;
	N=1;
	if -y3>=h
	  % The projectile is setting on the ground.
	  
	  phi3 = -abs(acos((h - l5*cos(phi2))/l3));
	  flag=0;
    end
    
	ymin=-h*1.1;
	ymax=(l5+l3)*1.1;
	xmin=-max([l1+l2,l5+l3])*1.1;
	xmax=-xmin;
	global xmin xmax ymin ymax
    phi1init=phi1;phi2init=phi2;phi3init=phi3;
    if flag2==1
        set(h_uic_15,'string','l1 has been reduced'),pause(2)
    end

elseif strcmp(command,'plot')
%    disp('plotting')
    phi1=parameter1;phi2=parameter2;phi3=parameter3;
    x1=-l2 * sin(phi2)+l1*sin(phi1);
	y1=l2 *cos(phi2)-l1 * cos(phi1);
	x4=-l2 * sin(phi2);
	y4=l2 * cos(phi2);
	x5=l5 * sin(phi2);
	y5=-l5 * cos(phi2);
	x3=l5 * sin(phi2)+l3 * sin(phi3);
	y3=-l5 * cos(phi2)-l3 * cos(phi3);
	
	ymin=-h*1.1;
	ymax=(l5+l3)*1.1;
	xmin=-max([l1+l2,l5+l3])*1.1;
	xmax=-xmin;

	if flag5==0
		tc=get(findobj('tag','trebdsgn'),'color');
		trlines=plot([x1  x4  x5  x3 ]',[y1  y4  y5  y3 ]');

		
			b=title('Trebuchet Designer 2.0');
			set(b,'tag','trtitle','fontunits','normal','fontsize',.075,...
			'fontweight','bold','fontangle','italic')
			set(b,'color',[1 1 1]-tc)
		

		
		axis('equal')		
		axis([xmin xmax ymin ymax])
%		axis('equal') 
		grid on
		ax=axis;
		xmin=ax(1);xmax=ax(2);ymin=ax(3);
		x1s= [-.1*h .1*h;0 0];y1s=[-h -h;0 0];z1s=[0 0;0 0];
		x2s=[xmin xmax;xmin xmax];y2s=[ymin ymin;-h -h];z2s=-[100 100;100 100];
	    x=[x1s;inf inf;x2s];y=[y1s;inf inf;y2s];z=[z1s-1000;0 0;z2s];
%		hold on
	%	surface(x,y,z)
	    patch([-.1*h .1*h 0 0]', [-h -h 0 0]',[0 0 0 0]'-1,'r')
	    patch( [xmin xmax xmax xmin]', [ymin ymin -h -h],[0 0 0 0]'-1,'g')
		set(trlines,'linewidth',2)
%		trlines=plot([x1  x4  x5  x3 ]',[y1  y4  y5  y3 ]');
        drawnow
		axis('equal')
		axis([xmin xmax ymin ymax])
%		axis('equal') 
%		drawnow
%		hold off
	  else
	    delete(trlines)
	    hold on
%		axis manual
	    trlines=plot([x1  x4  x5  x3 ]',[y1  y4  y5  y3 ]');
		set(trlines,'linewidth',2)
		axis([xmin xmax ymin ymax])
%		axis('equal')
	    hold off
	end
	flag5=1;
elseif nargin==2

	%Constrained section 
%	disp('Evaluating derivatives')
	z=parameter1;
	phi1=z(1);phi2=z(3);phi3=z(5);
	phi1d=z(2);phi2d=z(4);phi3d=z(6);
    y3t=-l5*cos(phi2)-l3*cos(phi3);
    y3td= l5*phi2d*sin(phi2)+l3*phi3d*sin(phi3);

	
	zd(1)=z(2);
	
	zd(3)=z(4);

%----------------------------------------------------------
%   If stuck on the ground and not going up

	if (y3t<=0) & (y3td<0)

		zd(5)= l5*sin(phi2)*phi2d/...
	   (l3*sqrt(1 - power(h - l5*cos(phi2),2)/power(l3,2)));
		
		zd(2)= (-((g*sin(phi1) - l2*sin(phi1 - phi2)*......
	          power(phi2d,2))/l1) - ...
	    l2*cos(phi1 - phi2)*(-(l1*l3*l5*m3*...
	           cos(acos((h - l5*cos(phi2))/l3) + phi2)*...
	           (-(g*sqrt(1 - power(h - l5*cos(phi2),2)/power(l3,2))) - ...
	             l5*sin(acos((h - l5*cos(phi2))/l3) + phi2)*...
	              power(phi2d,2))) + ...
	        l3*(l1*l2*m1*cos(phi1 - phi2)*...
	            (g*sin(phi1) - l2*sin(phi1 - phi2)*...
	               power(phi2d,2)) + ...
	           l1*(-(g*l2*m1*sin(phi2)) + g*l4*m2*sin(phi2) + ...
	              g*l5*m3*sin(phi2) + ...
	              l1*l2*m1*sin(phi1 - phi2)*...
	               power(phi1d,2) + ...
	              power(l5,3)*m3*power(sin(phi2),2)*...
	                sin(acos((h - l5*cos(phi2))/l3) + phi2)*...
	                power(phi2d,2)/...
	               (l3*(1 - power(h - l5*cos(phi2),2)/power(l3,2))))))/...
	     (l1*(l3*(l1*(J + power(l2,2)*m1 + power(l5,2)*m3) - ...
	            l1*power(l2,2)*m1*power(cos(phi1 - phi2),2)) - ...
	         l1*l3*power(l5,2)*m3*power(cos(acos((h - l5*cos(phi2))/l3) + ...
	             phi2),2))));
		
		
		
		zd(4)= (-((-(l1*l3*l5*m3*cos(acos((h - l5*cos(phi2))/l3) + phi2)*...
	           (-(g*sqrt(1 - power(h - l5*cos(phi2),2)/power(l3,2))) - ...
	             l5*sin(acos((h - l5*cos(phi2))/l3) + phi2)*...
	              power(phi2d,2))) + ...
	        l3*(l1*l2*m1*cos(phi1 - phi2)*...
	            (g*sin(phi1) - l2*sin(phi1 - phi2)*...
	               power(phi2d,2)) + ...
	           l1*(-(g*l2*m1*sin(phi2)) + g*l4*m2*sin(phi2) + ...
	              g*l5*m3*sin(phi2) + ...
	              l1*l2*m1*sin(phi1 - phi2)*...
	               power(phi1d,2) + ...
	              power(l5,3)*m3*power(sin(phi2),2)*...
	                sin(acos((h - l5*cos(phi2))/l3) + phi2)*...
	                power(phi2d,2)/...
	               (l3*(1 - power(h - l5*cos(phi2),2)/power(l3,2))))))/...
	      (l3*(l1*(J + power(l2,2)*m1 + power(l5,2)*m3) - ...
	           l1*power(l2,2)*m1*power(cos(phi1 - phi2),2)) - ...
	        l1*l3*power(l5,2)*m3*power(cos(acos((h - l5*cos(phi2))/l3) + ...
	            phi2),2))));
		
		
		zd(6)= (-((-(g*sqrt(1 - power(h - l5*cos(phi2),2)/power(l3,2))) - ...
	         l5*sin(acos((h - l5*cos(phi2))/l3) + phi2)*...
	          power(phi2d,2))/l3) + ...
	    l5*cos(acos((h - l5*cos(phi2))/l3) + phi2)*...
	      (-(l1*l3*l5*m3*cos(acos((h - l5*cos(phi2))/l3) + phi2)*...
	           (-(g*sqrt(1 - power(h - l5*cos(phi2),2)/power(l3,2))) - ...
	             l5*sin(acos((h - l5*cos(phi2))/l3) + phi2)*...
	              power(phi2d,2))) + ...
	        l3*(l1*l2*m1*cos(phi1 - phi2)*...
	            (g*sin(phi1) - l2*sin(phi1 - phi2)*...
	               power(phi2d,2)) + ...
	           l1*(-(g*l2*m1*sin(phi2)) + g*l4*m2*sin(phi2) + ...
	              g*l5*m3*sin(phi2) + ...
	              l1*l2*m1*sin(phi1 - phi2)*...
	               power(phi1d,2) + ...
	              power(l5,3)*m3*power(sin(phi2),2)*...
	                sin(acos((h - l5*cos(phi2))/l3) + phi2)*...
	                power(phi2d,2)/...
	               (l3*(1 - power(h - l5*cos(phi2),2)/power(l3,2))))))/...
	     (l3*(l3*(l1*(J + power(l2,2)*m1 + power(l5,2)*m3) - ...
	            l1*power(l2,2)*m1*power(cos(phi1 - phi2),2)) - ...
	         l1*l3*power(l5,2)*m3*power(cos(acos((h - l5*cos(phi2))/l3) + ...
	             phi2),2))));
		
		
		phi1dd=zd(2);phi2dd=zd(4);phi3dd=zd(6);
		N= (-((-(m3*cos(phi3)*(l5*sin(phi2)*...
	              power(phi2d,2) + ...
	             l3*sin(phi3)*power(phi3d,2) - ...
	             l5*cos(phi2)*phi2dd - ...
	             l3*cos(phi3)*phi3dd)) - ...
	        sin(phi3)*(-(g*m3) - ...
	           l5*m3*cos(phi2)*power(phi2d,2) - ...
	           l3*m3*cos(phi3)*power(phi3d,2) - ...
	           l5*m3*sin(phi2)*phi2dd - ...
	           l3*m3*sin(phi3)*phi3dd))/...
	      (mu*cos(phi3) - sin(phi3))));
		time=command;
	
		
		T= (m3*csc(phi3)*(l5*sin(phi2)*power(phi2d,2) + ...
	       l3*sin(phi3)*power(phi3d,2) - ...
	       l5*cos(phi2)*phi2dd - ...
	       l3*cos(phi3)*phi3dd) + ...
	    mu*csc(phi3)*(-(m3*cos(phi3)*...
	           (l5*sin(phi2)*power(phi2d,2) + ...
	             l3*sin(phi3)*power(phi3d,2) - ...
	             l5*cos(phi2)*phi2dd - ...
	             l3*cos(phi3)*phi3dd)) - ...
	        sin(phi3)*(-(g*m3) - ...
	           l5*m3*cos(phi2)*power(phi2d,2) - ...
	           l3*m3*cos(phi3)*power(phi3d,2) - ...
	           l5*m3*sin(phi2)*phi2dd - ...
	           l3*m3*sin(phi3)*phi3dd))/...
	     (mu*cos(phi3) - sin(phi3)));
	
	else    

		zd(5)=z(6);
		
	    zd(2)= (-((g*sin(phi1) - l2*sin(phi1 - phi2)*...
	          power(phi2d,2))/l1) - ...
	    l2*cos(phi1 - phi2)*(-(l1*l3*l5*m3*cos(phi2 - phi3)*...
	           (g*sin(phi3) - l5*sin(phi2 - phi3)*...
	              power(phi2d,2))) + ...
	        l3*(l1*l2*m1*cos(phi1 - phi2)*...
	            (g*sin(phi1) - l2*sin(phi1 - phi2)*...
	               power(phi2d,2)) + ...
	           l1*(-(g*l2*m1*sin(phi2)) + g*l4*m2*sin(phi2) + ...
	              g*l5*m3*sin(phi2) + ...
	              l1*l2*m1*sin(phi1 - phi2)*...
	               power(phi1d,2) + ...
	              l3*l5*m3*sin(phi2 - phi3)*...
	               power(phi3d,2))))/...
	     (l1*(l3*(l1*(J + power(l2,2)*m1 + power(l5,2)*m3) - ...
	            l1*power(l2,2)*m1*power(cos(phi1 - phi2),2)) - ...
	         l1*l3*power(l5,2)*m3*power(cos(phi2 - phi3),2))));
			
		zd(4)= (-((-(l1*l3*l5*m3*cos(phi2 - phi3)*...
	           (g*sin(phi3) - l5*sin(phi2 - phi3)*...
	              power(phi2d,2))) + ...
	        l3*(l1*l2*m1*cos(phi1 - phi2)*...
	            (g*sin(phi1) - l2*sin(phi1 - phi2)*...
	               power(phi2d,2)) + ...
	           l1*(-(g*l2*m1*sin(phi2)) + g*l4*m2*sin(phi2) + ...
	              g*l5*m3*sin(phi2) + ...
	              l1*l2*m1*sin(phi1 - phi2)*...
	               power(phi1d,2) + ...
	              l3*l5*m3*sin(phi2 - phi3)*...
	               power(phi3d,2))))/...
	      (l3*(l1*(J + power(l2,2)*m1 + power(l5,2)*m3) - ...
	           l1*power(l2,2)*m1*power(cos(phi1 - phi2),2)) - ...
	        l1*l3*power(l5,2)*m3*power(cos(phi2 - phi3),2))));
		
			zd(6)= (-((g*sin(phi3) - l5*sin(phi2 - phi3)*...
	          power(phi2d,2))/l3) + ...
	    l5*cos(phi2 - phi3)*(-(l1*l3*l5*m3*cos(phi2 - phi3)*...
	           (g*sin(phi3) - l5*sin(phi2 - phi3)*...
	              power(phi2d,2))) + ...
	        l3*(l1*l2*m1*cos(phi1 - phi2)*...
	            (g*sin(phi1) - l2*sin(phi1 - phi2)*...
	               power(phi2d,2)) + ...
	           l1*(-(g*l2*m1*sin(phi2)) + g*l4*m2*sin(phi2) + ...
	              g*l5*m3*sin(phi2) + ...
	              l1*l2*m1*sin(phi1 - phi2)*...
	               power(phi1d,2) + ...
	              l3*l5*m3*sin(phi2 - phi3)*...
	               power(phi3d,2))))/...
	     (l3*(l3*(l1*(J + power(l2,2)*m1 + power(l5,2)*m3) - ...
	            l1*power(l2,2)*m1*power(cos(phi1 - phi2),2)) - ...
	         l1*l3*power(l5,2)*m3*power(cos(phi2 - phi3),2))));
		
    end

    zd=zd';

	if time>lt
	       set(h_uic_15,'string',['t = ' num2str(time)])
	       lt=time;
	       drawnow
	end

    else 
	    error('Error: trebdsgn.m called with incorrect command.') 
end 
